export default function TermsOfService() {
    return (
        <div className="max-w-4xl mx-auto px-6 py-12 md:py-20 font-[var(--font-body)]">
            <h1 className="text-3xl md:text-4xl font-bold font-[var(--font-heading)] mb-8 tracking-widest text-[#1a1a1a]">TERMS OF SERVICE</h1>

            <div className="space-y-6 text-gray-700 leading-relaxed text-[15px]">
                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Introduction</h2>
                <p>Welcome to Shubhlaxmi. In using the service of Shubhlaxmi. You are deemed to have accepted the terms and conditions listed herein.</p>

                <p className="uppercase text-sm tracking-wide font-medium">PLEASE READ THESE TERMS OF USE ("AGREEMENT" OR "TERMS OF USE") CAREFULLY BEFORE USING THE WEBSITE AND SERVICES OFFERED BY ("Shubhlaxmi"). THIS AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF THE WEBSITE AT https://www.shubhlaxmi.com (THE "SITE") AND ALL SERVICES PROVIDED BY Shubhlaxmi. shubhlaxmi.com IS NOT AFFILIATED WITH ANY OTHER WEBSITE.</p>

                <p>All products/services and information displayed on Shubhlaxmi constitute an "invitation to offer". Your order for purchase constitutes your "offer" which shall be subject to the terms and conditions as listed below. Shubhlaxmi reserves the right to accept or reject your offer. If you have supplied us with your valid email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm details and therefore process the order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act or omission of Shubhlaxmi prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Eligibility for Membership</h2>
                <p>Use of the Site is available only to persons who can form legally binding contracts under applicable law. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. If you are a minor i.e. under the age of 18 years but at least 13 years of age, you may use this Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Use. If your age is below that of 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption, the sale or purchase of which to/by minors are strictly prohibited.</p>
                <p>Shubhlaxmi reserves the right to terminate your membership and refuse to provide you with access to the Site if Shubhlaxmi discovers that you are under the age of 18 years. The Site is not available to persons whose membership has been suspended or terminated by Shubhlaxmi for any reason whatsoever. If you are registering as a business entity, you represent that you have the authority to bind the entity to this User Agreement.</p>
                <p>Except where additional terms and conditions are provided which are product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of Shubhlaxmi you agree to be bound by the Terms and Conditions.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Account and Registration Obligations</h2>
                <p>"Your Information" is defined as any information you provide to us in the registration, buying or listing process, in the feedback area or through any email feature. We will protect Your Information in accordance with our Privacy Policy. If you use the Site, you are responsible for maintaining the confidentiality of Your Account and Password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under Your Account or Password. Shubhlaxmi shall not be liable to any person for any loss or damage which may arise as a result of any failure by you to protect your password or account. If you know or suspect that someone else knows your password, you should notify us by contacting us immediately through the address provided below. If Shubhlaxmi has reason to believe that there is likely to be a breach of security or misuse of the Shubhlaxmi Site, we may require you to change your password or we may suspend your account without any liability to Shubhlaxmi.</p>

                <p className="font-bold">You also agree to:</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li>Provide true, accurate, current and complete information about yourself in Shubhlaxmi's registration form (such information being the "Registration Data").</li>
                    <li>Maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, incomplete, or not current or if Shubhlaxmi has reasonable grounds to suspect that such information is untrue, inaccurate, not current or not in accordance with the User Agreement, Shubhlaxmi has the right to indefinitely suspend or terminate your membership and refuse to provide you with access to the Site.</li>
                </ul>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Pricing Information</h2>
                <p>While Shubhlaxmi strives to provide accurate product and pricing information, pricing or typographical errors may occur. Shubhlaxmi cannot confirm the price of a product until after you order. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, Shubhlaxmi shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event that an item is mis-priced, Shubhlaxmi may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been dispatched, your offer will not be deemed accepted and Shubhlaxmi will have the right to modify the price of the product and contact you for further instructions using the e-mail address provided by you during the time of registration, or cancel the order and notify you of such cancellation. In the event that Shubhlaxmi accepts your order the same shall be debited to your credit card account and duly notified to you by email that the payment has been processed. The payment may be processed prior to Shubhlaxmi dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed back to your credit card account.</p>
                <p>We strive to provide you with the best prices. However, sometimes a price online does not match the price in a store. In our effort to be the lowest price provider in your particular geographic region, store pricing may sometimes differ from online prices. Prices and availability are subject to change without notice.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Cancellation by Shubhlaxmi</h2>
                <p>Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being canceled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, the said amount will be reversed back in your Card Account.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Credit Card Details</h2>
                <p>You agree, understand and confirm that the credit card details provided by you for availing of services on Shubhlaxmi will be correct and accurate and you shall not use the credit card which is not lawfully owned by you, i.e. in a credit card transaction, you must use your own credit card. You further agree and undertake to provide the correct and valid credit card details when making payment on Shubhlaxmi. Your credit card information never reaches Shubhlaxmi, we just get a pass, hold or fail message from our payment gateways. The said information will not be utilised and shared by our payment gateways or Shubhlaxmi with any of the third parties unless required for fraud verifications or by law, regulation or court order. Shubhlaxmi will not be liable for any credit card fraud. The liability for use of a card fraudulently will be on you and the onus to 'prove otherwise' shall be exclusively on you.</p>
                <p>If you face any issues with the payment, you can inform us within 48 hours of the payment via call at: +9198985 76254 24/7 or email us at live@shubhlaxmi.co for quick chat now even you can whatsapp us at +9198985 76254</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Fraudulent / Declined Transactions</h2>
                <p>Shubhlaxmi reserves the right to recover the cost of goods, collection charges and lawyers fees from persons using the Site fraudulently. Shubhlaxmi reserves the right to initiate legal proceedings against such persons for fraudulent use of the Site and any other unlawful acts or acts or omissions in breach of these terms and conditions.</p>
                <p>We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Electronic Communications</h2>
                <p>When you visit the Site or send emails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Conditions for Customer Support Chat</h2>
                <p>Shubhlaxmi may suspend Shubhlaxmi live support service at any time without notice.</p>
                <p>Shubhlaxmi or its executives are not responsible for any delay caused in attending to or replying to the queries via chat.</p>
                <p>Any communication through chat may be stored by Shubhlaxmi for Shubhlaxmi reference; customers would not have the right to access this information at a later date.</p>
                <p>While chatting you may not put on any objectionable information i.e. unlawful, threatening, abusive, defamatory, obscene information.</p>
                <p>The chat room will not be used for selling any products or advising on business opportunities or any other form of solicitation.</p>
                <p>You may proceed further, and chat with our online customer care executive only if you agree to the above terms and conditions.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">You Agree and Confirm</h2>
                <ul className="list-disc pl-5 space-y-2">
                    <li>That in the event that a non-delivery occurs on account of a mistake by you (i.e. wrong name or address or any other wrong information) any extra cost incurred by Shubhlaxmi for redelivery shall be claimed from you.</li>
                    <li>That you will use the services provided by Shubhlaxmi, its affiliates and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using the Site and transacting on the Site.</li>
                    <li>You will provide authentic and true information in all instances where such information is requested of you. Shubhlaxmi reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), Shubhlaxmi has the right in its sole discretion to reject the registration and debar you from using the Services of Shubhlaxmi and / or other affiliated websites without prior intimation whatsoever.</li>
                    <li>That you are accessing the services available on this Site and transacting at your sole risk and are using your best and prudent judgment before entering into any transaction through this Site.</li>
                    <li>That the address at which delivery of the product ordered by you is to be made will be correct and proper in all respects.</li>
                    <li>That before placing an order you will check the product description carefully. By placing an order for a product you agree to be bound by the conditions of sale included in the item's description.</li>
                </ul>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">You may not use the Site for any of the following purposes:</h2>
                <ul className="list-disc pl-5 space-y-2">
                    <li>Disseminating any unlawful, harassing, libelous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material.</li>
                    <li>Transmitting material that encourages conduct that constitutes a criminal offence, results in civil liability or otherwise breaches any relevant laws, regulations or code of practice.</li>
                    <li>Gaining unauthorized access to other computer systems. Interfering with any other person's use or enjoyment of the Site.</li>
                    <li>Breaching any applicable laws;</li>
                    <li>Interfering or disrupting networks or web sites connected to the Site.</li>
                    <li>Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner.</li>
                </ul>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Modification of Terms & Conditions of Service</h2>
                <p>Shubhlaxmi may at any time modify the Terms & Conditions of Use of the site without any prior notification to you. You can access the latest version of the User Agreement at any given time on Shubhlaxmi. You should regularly review the Terms & Conditions on Shubhlaxmi. In the event the modified Terms & Conditions is not acceptable to you, you should discontinue using the service. However, if you continue to use the service you shall be deemed to have agreed to accept and abide by the modified Terms & Conditions of Use of this site.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Governing Law and Jurisdiction</h2>
                <p>This User Agreement shall be construed in accord with the applicable laws of India. The Courts at Surat shall have exclusive jurisdiction in any proceedings arising out of this agreement.</p>
                <p>Any dispute or difference either in interpretation or otherwise, of any terms of this User Agreement between the parties hereto, the same shall be referred to an independent arbitrator who will be appointed by Shubhlaxmi and his decision shall be final and binding on the parties hereto. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended time to time. The arbitration shall be held in Mumbai. The High Court of judicature at Surat alone shall have the jurisdiction and the Laws of India shall apply.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Reviews, Feedback, Submissions</h2>
                <p>All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to Shubhlaxmi on or by this Site or otherwise disclosed, submitted or offered in connection with your use of this Site (collectively, the "Comments") shall be and remain Shubhlaxmi property. Such disclosure, submission or offer of any Comments shall constitute an assignment to Shubhlaxmi of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, Shubhlaxmi owns exclusively all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments. Shubhlaxmi will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. Shubhlaxmi is and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay you any compensation for any Comments; or (3) to respond to any Comments. You agree that any Comments submitted by you to the Site will not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you to the Site will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam".</p>
                <p>Shubhlaxmi does not regularly review posted Comments, but does reserve the right (but not the obligation) to monitor and edit or remove any Comments submitted to the Site. You grant Shubhlaxmi the right to use the name that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any Comments you make and you agree to indemnify Shubhlaxmi and its affiliates for all claims resulting from any Comments you submit. Shubhlaxmi and its affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Force Majeure</h2>
                <p>Shubhlaxmi cannot be held liable for failure to fulfill one of its commitments to the Customer, if this failure is due to a case of force majeure such as war, strike (in-house or at one of its service providers), lock-out, accident, fire, ice, flood, bad weather, interruption or suspension of means of communication and/or transport, blockade, blockage of exports, prohibited import or export, cessation of production or delivery, regulatory decision of an administrative supervisory body, etc.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Copyright & Trademark</h2>
                <p>Shubhlaxmi and its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Site. Access to this Site does not confer and shall not be considered as conferring upon anyone any license under any of Shubhlaxmi or any third party's intellectual property rights. All rights, including copyright, in this website are owned by or licensed to Shubhlaxmi or third party suppliers. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of Shubhlaxmi. You can not modify, distribute or re-post anything on this website for any purpose.</p>
                <p>The Shubhlaxmi names and logos and all related product and service and Shubhlaxmi slogans are the trademarks or service marks of Shubhlaxmi. All other marks are the property of their respective companies. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.</p>
                <p>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Site (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Site for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Site or any related software. All software used on this Site is the property of Shubhlaxmi or its suppliers and protected by Indian and international copyright laws. The Contents and software on this Site may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Site is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks and/or other intellectual property owned, controlled or licensed by Shubhlaxmi ,one of its affiliates or by third parties who have licensed their materials to Shubhlaxmi and are protected by Indian and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this Site is the exclusive property of Shubhlaxmi and is also protected by Indian and international copyright laws.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Objectionable Material</h2>
                <p>You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that to the fullest extent permitted under applicable law, Shubhlaxmi and its affiliates shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable to you.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Indemnity</h2>
                <p>You agree to defend, indemnify and hold harmless Shubhlaxmi, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to Shubhlaxmi or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Termination</h2>
                <p>This User Agreement is effective unless and until terminated by either you or Shubhlaxmi. You may terminate this User Agreement at any time, provided that you discontinue any further use of this Site. Shubhlaxmi may terminate this User Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site, Such termination will be without any liability to Shubhlaxmi. Upon any termination of the User Agreement by either you or Shubhlaxmi, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the User Agreement or otherwise. Shubhlaxmi's right to any Comments shall survive any termination of this User Agreement. Any such termination of the User Agreement shall not cancel your obligation to pay for the product already ordered from the Site or affect any liability that may have arisen under the User Agreement.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Limitation of Liability and Disclaimers</h2>
                <p>The Site is provided without any warranties or guarantees and in an "As Is" condition. You must bear the risks associated with the use of the Site.</p>
                <p>The Site provides content from other Internet sites or resources and while Shubhlaxmi tries to ensure that material included on the Site is correct, reputable and of high quality, it cannot accept responsibility if this is not the case. Shubhlaxmi will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems you may experience with the Site. This disclaimer does not apply to any product warranty offered by the manufacturer of the product as specified in the product specifications. This disclaimer constitutes an essential part of this User Agreement. To the fullest extent permitted under applicable law, Shubhlaxmi or its suppliers shall not be liable for any indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Site, its services or this User Agreement. Without prejudice to the generality of the section above, the total liability of Shubhlaxmi to you for all liabilities arising out of this User Agreement be it in tort or contract is limited to the value of the product ordered by you. Shubhlaxmi, its associates and technology partners make no representations or warranties about the accuracy, reliability, completeness, correctness and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Site or that the operation of the Site will be error free and/or uninterrupted. Consequently, Shubhlaxmi assumes no liability whatsoever for any monetary or other damage suffered by you on account of the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Site; and/or any interruption or errors in the operation of the Site.</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Site Security</h2>
                <p>You are prohibited from violating or attempting to violate the security of the Site, including, without limitation, (a) accessing data not intended for you or logging onto a server or an account which you are not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, "flooding," "spamming," "mailbombing" or "crashing;" (d) sending unsolicited email, including promotions and/or advertising of products or services; or (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability. Shubhlaxmi will investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from Shubhlaxmi on this Site and other than generally available third party web browsers (e.g., Netscape Navigator, Microsoft Explorer).</p>

                <h2 className="text-xl font-bold text-[#1a1a1a] mt-8 mb-4">Entire Agreement</h2>
                <p>If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. Unless otherwise specified herein, this agreement constitutes the entire agreement between you and Shubhlaxmi with respect to the Shubhlaxmi sites/services and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and Shubhlaxmi with respect to the Shubhlaxmi sites/services. Shubhlaxmi's failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches.</p>
            </div>
        </div>
    );
}
